accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),    
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<username>/follow', views.follow, name='follow'),

]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/update/', views.update, name='update'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:movie_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:movie_pk>/likes/', views.likes, name='likes'),


]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
         
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/models.py
from django.conf import settings
from django.db import models

# Create your models here.
class Movie(models.Model):

    title = models.CharField(max_length=20)
    audience = models.IntegerField()
    release_date = models.DateField()
    genre = models.CharField(max_length=30)
    score = models.FloatField()
    post_url = models.CharField(max_length=50)
    description = models.TextField()
    actor_image = models.ImageField(blank=True)

    user= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')



class Comment(models.Model):

    content = models.CharField(max_length=100)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

movies/forms.py
from django import forms
from .models import Movie, Comment


class MovieForm(forms.ModelForm):

    # 영화 세부내용 폼 
    select = [
        ('comedy', 'comedy'),
        ('thriller', 'thriller'),
        ('romance', 'romance'),
        ('action', 'action'),
        ('horror', 'horror'),
        ('fantasy', 'fantasy'),
        ('musical', 'musical'),
    ]
    genre = forms.ChoiceField(choices = select)
    score = forms.FloatField(required=False, max_value=5, min_value=0,widget=forms.NumberInput(attrs={'step':'0.5'}))
    release_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Movie
        exclude = (
            'user',
            'like_users',
        )


class CommentForm(forms.ModelForm):
    

    class Meta:
        model = Comment
        fields = ('content',)

    

movies/views.py
from django.shortcuts import render, redirect
from .models import Movie, Comment
from .forms import MovieForm, CommentForm
from django.views.decorators.http import require_GET, require_http_methods, require_safe, require_POST


# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {'movies':movies}
    return render(request, 'movies/index.html', context)

def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES)
        if form.is_valid():
            movie = form.save(commit=False)
            movie.user = request.user
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()

    context = {'form':form}
    return render(request, 'movies/create.html', context)

def detail(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    comment_form = CommentForm()
    comments = movie.comment_set.all()
    context = {'movie':movie,
               'comment_form': comment_form,
                'comments': comments,
               }
    return render(request, 'movies/detail.html', context)

def update(request, movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    
    if not request.user.is_authenticated:
        return redirect('movies:detail', movie_pk)
    if request.method == 'POST':
        form = MovieForm(request.POST, request.FILES, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', movie_pk)
    else:
        form = MovieForm(instance=movie)

    context = {'form': form, 'movie': movie}
    return render(request, 'movies/update.html', context)

def delete(request, movie_pk):

    movie = Movie.objects.get(pk=movie_pk)
    if request.user == movie.user:
        movie.delete()
        return redirect('movies:index')
    return redirect('movies:deatil', movie.pk)


def comments_create(request, movie_pk):
    
    if not request.user.is_authenticated:
        return redirect('accounts:login')

    movie = Movie.objects.get(pk=movie_pk)
    comment_form = CommentForm(request.POST)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.movie = movie
        comment.user = request.user
        comment.save()
    return redirect('movies:detail', movie_pk)

def comments_delete(request, movie_pk, comment_pk):
    if not request.user.is_authenticated:
            return redirect('accounts:login')
    
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('movies:detail', movie_pk)


@require_POST
def likes(request, movie_pk):
    if request.user.is_authenticated:
        movie = Movie.objects.get(pk=movie_pk)

        if movie.like_users.filter(pk=request.user.pk).exists():
            movie.like_users.remove(request.user)
        else:
            movie.like_users.add(request.user)
        return redirect('movies:detail', movie_pk)
    return redirect('accounts:login')

movies/templates/movies/create.html
{% extends 'base.html' %}
{% block content %}
  {% load bootstrap4 %}



  <div class="w-50 rounded mx-auto mt-5 border border-light p-5">
    <h1 class="bold">글쓰기✏️</h1>
    <br>
  <form action="{% url 'movies:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% comment %} <input class="text-dark" type="submit" value="submit"/> {% endcomment %}
    <br>
    <div class="d-flex justify-content-between">
      <a class="text-dark">
        <input style="border-radius: 15px" class="bg-primary index medium text-white p-2" type="submit" value="작성하기"/>
      </a>
    </form>
  
  
    <a class="text-dark" href="{% url 'movies:index' %}">
      <input style="border-radius: 15px" class="p-2 index medium text-dark" type="button" value="뒤로가기"/>
    </a>
    </div>

  </div>

{% endblock content %}

movies/templates/movies/detail.html
{% extends 'base.html' %}{% load static %} {% load bootstrap4 %}
{% block content %}
<hr class="mt-5 mb-4" style="border-top: 5px dotted;">

<h1 style="font-size:60px;" class="medium text-center">{{movie.title}}</h1>

<!-- 하트와 작성자 표기 자현이의 도전.. -->
{% if request.user.is_authenticated %}
<div class="row">
  <dir class="col-lg-4"></dir>
    <form class="col-lg-4 mt-3 text-lg-center text-center" action="{% url 'movies:likes' movie.pk %}" method="POST">
      {% csrf_token %}
      {% if request.user in movie.like_users.all %}
        <input style="width:45px;" type="image" src="{% static 'heartt.png' %}" type="submit">
      {% else %}
        <input style="width:45px;" type="image" src="{% static 'heart3.png' %}" type="submit">
      {% endif %}
    </form>
    <!-- 작성자 표기-->
  
    {% if request.user == movie.user %}
      <div class="medium col-lg-4 mt-3 text-lg-end text-light">작성자 : <a class="text-light" href="{% url 'accounts:profile' movie.user.username %}">{{movie.user.username}}</a>
      <!-- 작성자일경우 업데이트 및 삭제 기능 추가-->

      <div>
        <a href="{% url 'movies:update' movie.pk %}">
          <input class="bg-info text-white m-2 mx-1" type="submit" value="UPDATE" style="border-radius:25px;"/></a>
        <a href="{% url 'movies:delete' movie.pk %}">
          {% csrf_token %}
          <input class="bg-danger text-white m-2 mx-1" type="submit" value="DELETE" style="border-radius:25px;"/></a>
      </div></div>
    {% else %}
    <div class="medium col-lg-4 mt-4 text-lg-end text-light">작성자 : <a class="text-light" href="{% url 'accounts:profile' movie.user.username %}">{{movie.user.username}}</a>
    </div>
    {% endif %}

{% else %}
<div class="medium mt-3 text-lg-end text-light">작성자 : <a class="text-light" href="{% url 'accounts:profile' movie.user.username %}">{{movie.user.username}}</a>
  </div>


{% endif %}



<hr class="my-4" style="border-top: 5px dotted;">
{% comment %} <hr align="center" style="width:160px; border:0px; border-top:5px dotted; margin-left:auto; margin-right:auto; margin-bottom:0px;"> {% endcomment %}

<div class="d-flex justify-content-center">
  <div>
  {% if movie.actor_image %}
    <img class="p-5 me-3" style="border-radius:50px; width:600px;" src="{{movie.actor_image.url}}"/>
  {% endif %}
  </div>

  <div class="p-5 ms-3">
  <div class="d-flex"><h1 class="medium me-2">관객수 </h1><h1>: {{movie.audience}}명</h1></div>
  <div class="d-flex"><h1 class="medium me-2">개봉일 </h1><h1>: {{movie.release_date}}</h1></div>
  <div class="d-flex"><h1 class="medium me-2">장르 </h1><h1>: {{movie.genre}}</h1></div>
  <div class="d-flex"><h1 class="medium me-2">평점 </h1><h1>: {{movie.score}} / 5.0</h1></div>
  <h1 class="medium me-2">줄거리 </h1><h1>{{movie.description}}</h1>
  <br>
  <h5>Poster URL : {{movie.post_url}}</h5>
  <!-- 사용자만 업데이트 가능하게 하기 -->
  <br><hr>

  <!-- 댓글 보기 -->
  <br>
  <p style="font-size:25px;">[댓글]</p>
  <ul>
      {% for comment in comments %}
      <li style="font-size:20px;">
        <div class="d-flex">
          <a style="text-decoration:none;" class="medium text-white" href="{% url 'accounts:profile' comment.user %}">{{comment.user}}</a> : {{comment.content}}
        <!-- 댓글 작성자일경우 삭제 기능 추가 -->
        {% if request.user == comment.user %}
          <form action="{% url 'movies:comments_delete' movie.pk comment.pk%}" method="POST">
            {% csrf_token %}
            <input style="font-size:15px; background-color: #FF5675; border-radius:25px;" class="ms-2 medium opacity-75 text-white" type="submit" value="DELETE">
          </form></div>
        {% endif %}
      </li>
      {% empty %}
      <p style="font-size:20px;" >첫 댓글을 남겨보세요 !</p>
    {% endfor %}
  </ul>
  <br>
  <!-- 댓글 쓰기 -->
  {% if request.user.is_authenticated %}
    <div >
    <form class="d-flex justify-content-center" action="{% url 'movies:comments_create' movie.pk %}" method="POST">
      {% csrf_token %}
      <div style="margin-right:10px;" class="w-75">
      {% bootstrap_form comment_form %}</div>
      <input style="background-color:	#1478CD; height:35px; margin-top:20px;" class="btn text-white" type="submit" value="댓글달기">
      {% comment %} <input type="checkbox" class="btn-check" id="btn-check-outlined" autocomplete="off">
      <label class="btn btn-outline-primary" for="btn-check-outlined">SAVE</label><br> {% endcomment %}
    </form>      
    </div>
  {% else %}
    <a class="medium" style="font-style:italic; font-size:18px;" href="{% url 'accounts:login' %}">로그인 후 댓글을 쓸 수 있습니다.</a>
    <br>
  {% endif %}
  
  <br>
  <a class="medium" style="color: #1478CD; font-size:18px;" href="{% url 'movies:index' %}">뒤로가기</a>
 </div>
</div>
{% endblock content %}

movies/templates/movies/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
{% comment %} <h1 class="bold pt-3 text-white m-3 mt-0 text-center">INDEX</h1>
<hr align="center" style="width:160px; border:0px; border-top:5px dotted; margin-left:auto; margin-right:auto; margin-bottom:0px;">
 {% endcomment %}

{% comment %} <a class="text-white" href="{% url 'movies:create' %}">CREATE</a> {% endcomment %}
<div class="mb-0 px-2 mx-4 text-start">
<a class="mb-0 text-dark" href="{% url 'movies:create' %}">
  {% comment %} <input style="border-radius: 15px" class="mb-0 btn btn-primary text-white medium mt-0 text-dark m-2 mx-3" type="button" value="Create"/> {% endcomment %}
  <input class="opacity-75" style="width:30px;" type="image" src="{% static 'plus.png' %}" type="submit">
</a>
<hr style="border-top: 3px dotted;">
</div>


{% for movie in movies %}

<div class="d-flex justify-content-start">
  <div>
{% if movie.actor_image %} <!--만약 이미지가 있으면 조건문 들어감-->
  <a href="{% url 'movies:detail' movie.pk %}"><img style="width:470px;" class="m-5" src="{{movie.actor_image.url}}" alt=""></a> <!--이미지태그 통과-->
{% endif %}
  </div>

  <div class="m-5 d-flex flex-column justify-content-center text-left">
    <a style="font-size:55px; text-decoration: none;" class="medium text-left text-white mb-4" href="{% url 'movies:detail' movie.pk %}">{{movie.title}}</a>
    <div>
      {% if movie.score == 1 %}
      <img style="width: 70px" src="{% static 'star.png' %}"/>
      {% elif movie.score == 1.5 %}
      <img style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 35px" src="{% static 'half_star.png' %}"/>
      {% elif movie.score == 2 %}
      <img style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 70px" src="{% static 'star.png' %}"/>
      {% elif movie.score == 2.5 %}
      <img style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 35px" src="{% static 'half_star.png' %}"/>
      {% elif movie.score == 3 %}
      <img style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 70px" src="{% static 'star.png' %}"/>
      {% elif movie.score == 3.5 %}
      <img style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 35px" src="{% static 'half_star.png' %}"/>
      {% elif movie.score == 4 %}
      <img style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 70px" src="{% static 'star.png' %}"/>
      {% elif movie.score == 4.5 %}
      <img style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 35px" src="{% static 'half_star.png' %}"/>
      {% elif movie.score == 5 %}
      <img style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 70px" src="{% static 'star.png' %}"/>
      <img class="ms-2" style="width: 70px" src="{% static 'star.png' %}"/>
      {% endif %}
    </div>
    <br>
    <p style="font-size:30px;">{{movie.description}}</p>
  </div>
</div>

  
    {% comment %} <hr style=
    "background:pink;
    height:1px;
    border:0;"> {% endcomment %}


<hr>
{% comment %} {% if movie.title != '비긴어게인' %} {% endcomment %}
{% comment %} {% endif %} {% endcomment %}

{% endfor %}

{% endblock content %}

movies/templates/movies/update.html
{% extends 'base.html' %}
{% block content %}
  {% load bootstrap4 %}
  <hr/>
  <div>
  <form action=" {% url 'movies:update' movie.pk %} " method="POST" enctype="multipart/form-data" class="w-50  rounded mx-auto mt-5 border border-light p-5">
    {% csrf_token %}
    <h1 class="bold">수정하기✏️</h1>
    <br>
    {% bootstrap_form form %}
    <input type="reset" value="Reset" class="text-white bg-danger mt-3" style="border-radius: 15px"/>
    <input type="submit" value="Submit" class="text-white bg-success mt-3" style="border-radius: 15px"/>
  
  <hr/>
  <a class="d-flex justify-content-end" style="text-decoration: none;" href="{% url 'movies:index' %}">
    <input style="border-radius: 15px" class="index medium text-dark" type="button" value="뒤로가기"/>
  </a></form>
  </div>
  {% comment %} <a sytle="color: #1478CD;" href="{% url 'movies:detail' movie.pk %}">뒤로가기</a> {% endcomment %}
{% endblock content %}