accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),    
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<username>/follow', views.follow, name='follow'),

]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/update/', views.update, name='update'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:movie_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:movie_pk>/likes/', views.likes, name='likes'),


]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
         
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# 이름규칙
# 앱 이름_모델클래스명_필드명
# movies_like_users_


# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    

movies/models.py
from django.conf import settings
from django.db import models

# Create your models here.
class Movie(models.Model):

    title = models.CharField(max_length=20)
    audience = models.IntegerField()
    release_date = models.DateField()
    genre = models.CharField(max_length=30)
    score = models.FloatField()
    post_url = models.CharField(max_length=50)
    description = models.TextField()
    actor_image = models.ImageField(blank=True)

    user= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')



class Comment(models.Model):

    content = models.CharField(max_length=100)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'first_name', 'last_name')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model

#
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.http import require_POST, require_safe, require_http_methods, require_GET
from .forms import CustomUserChangeForm, CustomUserCreationForm

# Create your views here.
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    else:
        if request.method == 'POST':
            form = AuthenticationForm(request, request.POST)
            if form.is_valid():
                auth_login(request, form.get_user())
                return redirect('movies:index')
        else:
            form = AuthenticationForm()

        context = {'form': form}
        return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('movies:index')

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()

    context = {'form': form}
    return render(request, 'accounts/signup.html', context)

@require_http_methods(['POST'])
def delete(request):
    #로그아웃 먼저 하면 삭제할 유저 정보가 없어짐
    request.user.delete()
    auth_logout(request) #유저 먼저 지우고 로그아웃
    return redirect('movies:index')



def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else: 
        form = CustomUserChangeForm(instance=request.user)
    context = {'form': form}
    return render(request, 'accounts/update.html', context)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            #다 바꾸고 세션 업데이트해줌
            update_session_auth_hash(request, form.user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {'form': form}
    return render(request, 'accounts/change_password.html', context)


def profile(request, username):
    person = get_user_model().objects.get(username=username)
    context = {
        'person':person
    }
    return render(request, 'accounts/profile.html', context)


@require_POST
def follow(request, username):
    if request.user.is_authenticated:

        person = get_user_model().objects.get(pk=username)
        if person != request.user:
            if person.followers.filter(pk=request.user.pk).exists():
                person.followers.remove(request.user)
            else:
                person.followers.add(request.user)
        return redirect('accounts:profile', person.username)
    return redirect('accounts:login')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% block content %}{% load bootstrap4 %}
<div style="width:620px;" class="rounded mx-auto mt-5 border border-light p-5">
  <h1 class="bold">비밀번호변경</h1>
  <br>
  <form action="{% url 'accounts:change_password' %}" method="POST">
    {% csrf_token %}{% bootstrap_form form%}
    {% comment %} {{form.as_p}} {% endcomment %}
    <div class="d-flex justify-content-between">
    <input type="submit" class="text-white bg-danger mt-3" style="border-radius: 15px" value="변경하기"/>
  
  <a class="text-white mt-3" href="{% url 'movies:index' %}">목록보기</a></form>
</div></div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}{% load bootstrap4 %}

  <div style="width:400px;" class="rounded mx-auto mt-5 border border-light p-5">

  <form class="text-white" action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    <div class="medium">{% bootstrap_form form %}</div>
    <br>
    {% comment %} <input class="text-dark" type="submit" value="Login"/> {% endcomment %}

    <a style="text-decoration: none;" class="d-flex justify-content-center">
      <input style="border-radius: 15px" class="bg-primary index medium text-white" type="submit" value="Login"/>
    </a>

  </form>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}

  <h1 class="bold">{{person.username}}님의 프로필</h1>

  <div>
    팔로잉 :
    {{person.followings.count}}
    | 팔로워 :
    {{person.followers.count}}
  </div>
  <br>

  <!--요청한 유저가 로그인된 유저가 아닐 경우 -->
  {% if request.user != person %}
    <form action="{% url 'accounts:follow' person.pk %}" method="POST">
      {% csrf_token %}
      {% if request.user in person.followers.all %}
        <button type="submit" class="btn btn-danger">언팔로우</button>
      {% else %}
        <button type="submit" class="btn btn-info text-white">팔로우</button>
      {% endif %}
    </form>
  {% endif %}

  <hr><br>
  <!-- 역참조 해야함 -->
  <h4 class="medium">작성한 게시글</h4>
  {% for movie in person.movie_set.all %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{movie.title}}</h5>
        <p class="card-text">{{movie.content}}</p>
        <a href="{% url 'movies:detail' movie.pk%}" class="btn btn-primary">자세히보기</a>
      </div>
    </div>
    <br>
  {% endfor %}

  <hr><br>
  <h4 class="medium">좋아한 게시글</h4>
  {% for movie in person.like_movies.all %}
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{movie.title}}</h5>
        <p class="card-text">{{movie.content}}</p>
        <a href="{% url 'movies:detail' movie.pk %}" class="btn btn-primary">자세히보기</a>
      </div>
    </div>
    <br>

  {% endfor %}
  <hr><br>
  <a href="{% url 'movies:index' %}" style="background-color:#288CD2" class="btn btn-success">목록보기</a>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
  {% load bootstrap4 %}

  <div style="width:620px;" class="rounded mx-auto mt-5 border border-light p-5">

  <form class="text-white" action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    <div class="medium">
      {% bootstrap_form form %}</div>
    
    <div class="d-flex justify-content-between">
    <a class="text-dark">
      <input style="border-radius: 15px" class="bg-primary index medium text-white" type="submit" value="Signup"/>
    </a>
  </form>



  <a class="text-dark" href="{% url 'movies:index' %}">
    <input style="border-radius: 15px" class="index medium text-dark" type="button" value="Back"/>
  </a>
  </div>
  </div>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% block content %} {% load bootstrap4 %}

  <div style="width:620px;" class="rounded mx-auto mt-5 border border-light p-5">

    <div class="text-white">
      <form action="{% url 'accounts:update' %}" method="POST">
        {% csrf_token %}{% bootstrap_form form %}
        {% comment %} {{form.as_p}} {% endcomment %}
        <br>
        <div class="d-flex justify-content-between">
          <input style="border-radius: 15px" class="bg-primary index medium text-white" type="submit" value="Update"/>
          <a class="text-white medium" href="{% url 'movies:index' %}">Back</a>
        </div>
      </form>
      
    </div>
  </div>

{% endblock content %}