accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),    
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<username>/follow', views.follow, name='follow'),

]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/update/', views.update, name='update'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:movie_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:movie_pk>/likes/', views.likes, name='likes'),


]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
         
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %} {% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;700;900&display=swap" rel="stylesheet">
    <style>
      .index {
        background: #F9FFFF;
      }

      * {
        font-family: "Noto Sans KR", sans-serif;
        color: white;
        background-color: #212529;
      }

      .bold {
        font-weight: 900;
      }

      .medium {
        font-weight: 700;
      }

      .light {
        font-weight: 100;
      }

      .heart {
        background-image:url({% static 'heart2.png' %});
        background-size:50px;
        background-repeat:no-repeat;
      }
    </style>
    {% comment %}
    <link rel="stylesheet" href="{% static 'base.css' %}" />
    {% endcomment %}
    <title>영화 리뷰</title>
  </head>

  <body class="bg-dark">
    <div>
        <div class="text-end mt-2 mx-2" id="nav">
          {% if user.is_authenticated %}
          <div class="d-flex flex-row justify-content-end">
          <h2 class="mt-2 mx-3 bold text-white" id="user-hello"><i>가보자고, <a class="text-white"href="{% url 'accounts:profile' user.username %}">{{user}}</a></i></h2>

          <a class="text-dark" href="{% url 'accounts:update' %}">
            <input
              style="border-radius: 15px"
              class="index medium text-dark m-3 mx-1"
              type="button"
              value="Update"
            />
          </a>

          <a class="text-dark" href="{% url 'accounts:logout' %}">
            <input
              style="border-radius: 15px"
              class="index medium text-dark m-3 mx-1"
              type="button"
              value="Logout"
            />
          </a>

          <form action="{% url 'accounts:delete' %}" method="POST">
            {% csrf_token %}
            <input class="medium bg-danger text-white m-3 mx-1 me-2" type="submit" value="Delete ID"/>
          </form>

          </div>

          {% else %}
          <a class="text-dark" href="{% url 'accounts:signup' %}">
            <input
              style="border-radius: 15px"
              class="index medium text-dark m-3 mx-0"
              type="button"
              value="Signup"
            />
          </a>

          <a class="text-dark" href="{% url 'accounts:login' %}">
            <input
              style="border-radius: 15px"
              class="index medium text-dark m-3"
              type="button"
              value="Login"
            />
          </a>
          {% endif %}
        </div>
      </div>

      <div class="bg-dark d-flex justify-content-center">
        <a href="{% url 'movies:index' %}">
          <img
            class="mb-0"
            style="width: 300px"
            src="{% static 'logo.png' %}"
            alt=""
          />
        </a></div>

      <div class="bg-dark px-5" id="content">{% block content %}{% endblock content %}</div>
      <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"
      ></script>
    </div>
  </body>
  <footer><p style="font-size:14px;" class="text-center mt-5">LGYJH © GAZA Studio Corp. All rights reserved.</p></footer>
</html>